title: Página personal de Álvaro Rojas
author: Álvaro Rojas
email: alvaro.rojas.wm@gmail.com
description: > Ordendores, filosofía y ciencia ficción.# this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: alvarettos # DO NOT include the @ character, or else the build will fail!
github_username:  alvaro-sudo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
