title: Álvaro Rojas Personal Blog
author: Álvaro Rojas
email: alvaro.rojas.wm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Página dedicada a temas de filosofía, ordenadores, ciencia ficción y música.

# social links
twitter_username: alvarettos # DO NOT include the @ character, or else the build will fail!
github_username:  alvaro-sudo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
